### ISSUE TITLE
AttributeError on list_projectnames_perstage 

### ISSUE THREAD

**Issue by jjmurre** [devpi/devpi-findlinks#6]
When using the +findlinks view with devpi-server 4.1.0 I am getting the following traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/views.py", line 146, in **call**
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 236, in **call**
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/views.py", line 169, in request_log_handler
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/views.py", line 204, in request_tx_handler
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(_attrs['exc_info'])
  File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python2.7/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 393, in attr_view
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 371, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/devpi_findlinks/main.py", line 25, in findlinks_view
    for stage, names in context.stage.op_sro("list_projectnames_perstage"):
  File "/usr/local/lib/python2.7/dist-packages/devpi_server/model.py", line 512, in op_sro
    yield stage, getattr(stage, opname)(_*kw)
AttributeError: 'PrivateStage' object has no attribute 'list_projectnames_perstage'

**Comment by fschulze** [comment]
Fixed with release 2.0.0.
