### ISSUE TITLE
error with link.eggfragment with devpi version 5.10

### ISSUE THREAD

**Issue by VicenteIranzoMaestre** [devpi/devpi-findlinks#8]
When asking for /{user}/{index}/+findlinks I get the following error:

`2019-11-21 19:44:52,512 ERROR Exception while serving /ploneteam/prod/+findlinks
Traceback (most recent call last):
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
    response = request.invoke_exception_view(exc_info)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
    raise HTTPNotFound
pyramid.httpexceptions.HTTPNotFound: The resource could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/waitress/channel.py", line 356, in service
    task.service()
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/waitress/task.py", line 172, in service
    self.execute()
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/waitress/task.py", line 440, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/devpi_server/views.py", line 151, in __call__
    return self.app(environ, start_response)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
    response = self.execution_policy(environ, self)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
    return request.invoke_exception_view(reraise=True)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
    reraise_(*exc_info)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
    return router.invoke_request(request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
    response = handle_request(request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/devpi_server/views.py", line 175, in request_log_handler
    response = handler(request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/devpi_server/views.py", line 211, in request_tx_handler
    response = handler(request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
    response = _error_handler(request, exc)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
    reraise(*exc_info)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
    raise value
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
    response = handler(request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
    response = view_callable(context, request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/config/views.py", line 188, in attr_view
    return view(context, request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper
    return view(context, request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response
    result = view(context, request)
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/devpi_findlinks/main.py", line 40, in findlinks_view
    if link.eggfragment:
  File "/Dades/pypi/venv_pypi/lib/python3.6/site-packages/devpi_server/model.py", line 1243, in __getattr__
    raise AttributeError(name)
AttributeError: eggfragment
`
ELink object doesn't have eggfragment property.

As a workaround I modified devpi_findlinks/main.py lines 40+
                key = link.basename
\#                if link.eggfragment:
\#                    key = link.eggfragment
\#               else:
\#                    key = link.basename

**Comment by VicenteIranzoMaestre** [comment]
I tried to generate pull request but I don't have enough permissions.
Thanks for your attention :)

**Comment by hpk42** [comment]
you probably need to fork it first to your home-location on github,
then do the PR from there.  You cannot create branches directly.

**Comment by fschulze** [comment]
Should be fixed with just released 2.0.1.
